-- UNFOUND G3 플레이테스트 로그 테이블
-- Supabase 대시보드 → SQL Editor에 이 파일 전체를 붙여넣고 Run 하면 끝난다.
--
-- 설계 원칙
--   1. 테이블 하나. 이벤트는 type + payload(jsonb)로 구분한다. 새 이벤트가 생겨도 스키마를 안 고친다
--   2. anon 키로는 INSERT만 된다. SELECT/UPDATE/DELETE 정책을 만들지 않으므로 전부 막힌다.
--      테스터가 키를 봐도 남의 로그를 읽거나 기존 행을 고칠 수 없다
--   3. 개인정보를 받지 않는다. session은 브라우저에서 만든 randomUUID다

create table if not exists public.play_events (
  id          bigint generated by default as identity primary key,
  session     text        not null,
  run         integer     not null default 0,
  ms          integer     not null default 0,
  turn        integer,
  type        text        not null,
  payload     jsonb       not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- 분석 쿼리가 항상 세션·종류로 걸리므로 그 두 개만 색인한다
create index if not exists play_events_session_idx on public.play_events (session, id);
create index if not exists play_events_type_idx    on public.play_events (type);
create index if not exists play_events_created_idx on public.play_events (created_at desc);

alter table public.play_events enable row level security;

-- 익명 삽입만 허용. 읽기 정책은 만들지 않는다 → anon은 SELECT 불가.
-- 대표는 대시보드(service_role)로 본다.
drop policy if exists "anon can insert play events" on public.play_events;
create policy "anon can insert play events"
  on public.play_events for insert
  to anon
  with check (
    length(session) between 8 and 64
    and length(type) <= 40
    and run  between 0 and 10000
    and ms   between 0 and 86400000
  );

-- ── 분석용 뷰 (대시보드에서 바로 보기) ──────────────────────────────

-- G3 기준 4종의 원재료. 세션 하나당 한 줄.
create or replace view public.playtest_sessions as
select
  session,
  min(created_at)                                              as started_at,
  max(created_at)                                              as last_seen,
  max(run)                                                     as runs,
  max(ms) / 60000.0                                            as session_min,
  min(ms) filter (where type = 'combine_ok')                   as first_combine_ms,
  count(*) filter (where type = 'combine_ok')                  as combines_ok,
  count(*) filter (where type = 'combine_fail')                as combines_failed,
  count(*) filter (where type = 'run_end'
                   and payload->>'result' = 'win')             as wins,
  count(*) filter (where type = 'run_end'
                   and payload->>'result' <> 'win')            as losses
from public.play_events
group by session;

-- 플레이어가 기대했지만 없던 조합. 다음 콘텐츠의 최고 근거다.
create or replace view public.playtest_missing_recipes as
select
  (select string_agg(x, ' + ' order by x)
     from jsonb_array_elements_text(payload->'inputs') as t(x)) as pair,
  count(*)                as tries,
  count(distinct session) as players
from public.play_events
where type = 'combine_fail'
  and payload->>'reason' = 'no_recipe'
group by 1
order by tries desc;

-- 어디서 죽는가 / 어디서 그만두는가
create or replace view public.playtest_run_ends as
select
  payload->>'result' as result,
  turn,
  count(*)           as runs
from public.play_events
where type = 'run_end'
group by 1, 2
order by 1, 2;
