-- UNFOUND G3 플레이테스트 로그 테이블 (v2.1 — 조합·경제 런)
-- Supabase 대시보드 → SQL Editor에 이 파일 전체를 붙여넣고 Run 하면 끝난다. 여러 번 돌려도 안전하다.
--
-- 설계 원칙
--   1. 테이블 하나. 이벤트는 type + payload(jsonb)로 구분한다. 새 이벤트가 생겨도 스키마를 안 고친다
--   2. anon 키로는 INSERT만 된다. SELECT/UPDATE/DELETE 정책을 만들지 않으므로 전부 막힌다.
--      테스터가 키를 봐도 남의 로그를 읽거나 기존 행을 고칠 수 없다
--   3. 개인정보를 받지 않는다. session은 브라우저에서 만든 randomUUID다
--
-- 2026-08-10 v2.1 개조: 전투가 사라져 run_end의 승패(result)가 없어졌다.
-- 이제 런의 성패는 계약이다 — payload.run_fail(불리언)과 fulfilled(이행 건수)로 본다.

create table if not exists public.play_events (
  id          bigint generated by default as identity primary key,
  session     text        not null,
  run         integer     not null default 0,
  ms          integer     not null default 0,
  turn        integer,
  type        text        not null,
  payload     jsonb       not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists play_events_session_idx on public.play_events (session, id);
create index if not exists play_events_type_idx    on public.play_events (type);
create index if not exists play_events_created_idx on public.play_events (created_at desc);

alter table public.play_events enable row level security;

-- 익명 삽입만 허용. 읽기 정책은 만들지 않는다 → anon은 SELECT 불가.
drop policy if exists "anon can insert play events" on public.play_events;
create policy "anon can insert play events"
  on public.play_events for insert
  to anon
  with check (
    length(session) between 8 and 64
    and length(type) <= 40
    and run  between 0 and 10000
    and ms   between 0 and 86400000
  );

-- ── G3 기준 4종 ────────────────────────────────────────────────
-- 자발적 2판 ≥50% / 첫 조합 ≤60초 / 세션 ≥15분 / 구매 의향 ≥30%(설문, 여기 없음)
-- 세션 하나당 한 줄.

create or replace view public.playtest_sessions as
select
  session,
  min(created_at)                                               as started_at,
  max(created_at)                                               as last_seen,
  max(run)                                                      as runs,
  max(ms) / 60000.0                                             as session_min,
  min(ms) filter (where type = 'combine_ok')                    as first_combine_ms,
  min(ms) filter (where type = 'sell')                          as first_sell_ms,
  min(ms) filter (where type in ('buy', 'hint'))                as first_buy_ms,
  count(*) filter (where type = 'combine_ok')                   as combines_ok,
  count(*) filter (where type = 'combine_ok'
                   and (payload->>'first_time')::boolean)       as discoveries,
  count(*) filter (where type = 'combine_fail')                 as combines_failed,
  count(*) filter (where type = 'hint')                         as hints_bought,
  count(*) filter (where type = 'deliver')                      as deliveries,
  count(*) filter (where type = 'run_end')                      as runs_ended,
  count(*) filter (where type = 'run_end'
                   and (payload->>'run_fail')::boolean)         as runs_failed
from public.play_events
group by session;

-- 게이트 판정용 한 줄 요약. 표본 10명이 차면 이 뷰만 보면 된다.
create or replace view public.playtest_gate as
select
  count(*)                                                          as players,
  avg(runs)                                                         as avg_runs,
  100.0 * count(*) filter (where runs >= 2) / nullif(count(*), 0)   as pct_two_runs,
  percentile_cont(0.5) within group (order by first_combine_ms)     as median_first_combine_ms,
  percentile_cont(0.5) within group (order by session_min)          as median_session_min,
  percentile_cont(0.25) within group (order by session_min)         as p25_session_min,
  percentile_cont(0.75) within group (order by session_min)         as p75_session_min
from public.playtest_sessions;

-- ── 플레이어가 기대했지만 없던 조합 — 다음 콘텐츠의 최고 근거 ──
-- signal='warm'은 계열이 맞는데 레시피가 없는 쌍이다. 여기가 1순위 후보다.

create or replace view public.playtest_missing_recipes as
select
  (select string_agg(x, ' + ' order by x)
     from jsonb_array_elements_text(payload->'inputs') as t(x)) as pair,
  payload->>'signal'      as signal,
  count(*)                as tries,
  count(distinct session) as players
from public.play_events
where type = 'combine_fail'
group by 1, 2
order by tries desc;

-- ── 어디서 그만두는가 / 무엇이 막았는가 ────────────────────────

create or replace view public.playtest_run_ends as
select
  (payload->>'run_fail')::boolean       as run_fail,
  (payload->>'fulfilled')::int          as contracts_done,
  count(*)                              as runs,
  avg((payload->>'settle')::numeric)    as avg_settle,
  avg((payload->>'combos')::numeric)    as avg_combos
from public.play_events
where type = 'run_end'
group by 1, 2
order by 1, 2;

-- 마찰: 눌렀는데 아무 일도 없었던 지점 + 규칙이 막은 지점.
-- 규칙이 이해되지 않는 곳이 여기에 쌓인다.
create or replace view public.playtest_friction as
select
  payload->>'reason'      as blocked_reason,
  turn,
  count(*)                as hits,
  count(distinct session) as players
from public.play_events
where type = 'combine_blocked'
group by 1, 2
order by hits desc;

-- 세션 요약 이벤트(session_summary)에 실린 무반응 클릭 집계.
create or replace view public.playtest_dead_clicks as
select
  d->>0                   as what,
  sum((d->>1)::int)       as clicks,
  count(distinct session) as players
from public.play_events,
     lateral jsonb_array_elements(payload->'dead_clicks') as d
where type = 'session_summary'
  and jsonb_typeof(payload->'dead_clicks') = 'array'
group by 1
order by clicks desc;
